<?php
	//CARA MENGGUNAKAN PHP
	//1. CODE EDITOR 
	//2. WEB SERVER (XAMPP, WAMPP, MAMPP)
	//3. DATABASE SERVER (DISINI MEMAKAI PHPMYADMIN)
	//4. BROWSER
	
	//LANGKAH:
	//SIMPAN FILE PHP DI DALAM DIREKTORI (FOLDER) xampp/htdocs YANG SUDAH DIINSTALL
	//NYALAKAN XAMPP (START APACHE)
	//BUKA BROWSER
	//ARAHKAN URL SEPERTI: localhost/nama_folder/file.php
	
    echo "Hello World";
?>